field_visibility_rules:
  type: objects
  default: []
  description: "List of field visibility rules. Each rule defines which groups can see which custom user field."
  schema:
    name: New Field
    identifier: field_name
    properties:
      field_name:
        type: string
        label: "Field Name"
        description: "The name of the custom user field (case-insensitive)"
        validations:
          min_length: 1
      allowed_groups:
        type: groups
        default: []
        label: "Allowed Groups"
        description: "Select groups that can see this field"
