field_visibility_rules:
  type: objects
  default:
    - field_name: company
      allowed_groups:
        - netwrix_employees
  description: "List of field visibility rules. Each rule defines which groups can see which custom user field."
  schema:
    name: field_visibility_rule
    properties:
      field_name:
        type: string
        validations:
          min_length: 1
      allowed_groups:
        type: list
        list_type: string
